### ISSUE TITLE
Contactarte

### ISSUE THREAD

**Issue by jaimegc** [alfonsodou/robocupcode#1]
Hola Alfonso, he intentado contactarte pero no consigo encontrarte en LinkedIn.

Mi duda era simplemente saber si tienes algo nuevo en mente con la JavaCup o ya te has pasado a la RoboCup de este proyecto, aunque o no pusheas o está parado quizás.

Mi LinkedIn lo puedes encontrar en mi perfil por si quieres que hablemos.

Un saludo!

**Comment by alfonsodou** [comment]
Hola Jaime, no tengo perfil en Linkedin, la verdad es que no me prodigo en redes sociales.

Mi idea es continuar con la JavaCup y este proyecto de robocupcode parte de la idea de usar el framework de robocode para adaptarlo y que ejecute partidos siguiendo más o menos las reglas de JavaCup.

Llevo unos meses con mucho trabajo y no avancé apenas, pero quiero seguir con ello. No te puedo dar una fecha estimada, ojalá pueda dedicarle más tiempo a partir de ahora y tener algo presentable antes de final de año.

Un saludo!

**Comment by jaimegc** [comment]
No tengo conocimiento de Robocode mas allá de la competición que es y no puedo imaginar como vas a combinarlo con la JavaCup. Me tocará esperar a ver los resultados, que seguro que son muy buenos.

Por mi parte, aunque nunca participé en la JavaCup pero sí la seguí de cerca. Allá por 2011 o así, intenté hacer un port a LibGDX con Android y conseguí ejecutar partidos aunque la UI tenía problemas y no se me veían algunas partes. No soy experto en librerías de este tipo y me costó un poco. Lo dejé ahí parado y siempre he tenido el gusanillo de hacer algo en mi tiempo libre.

Actualmente, al menos en la comunidad en la que me muevo, lo más "cool" es Kotlin en vez de Java. Ahora está la gente super motivada y haciendo muchas cosas. Se me ha pasado por la cabeza algún día portarlo a Kotlin y cambiar la librería de renderización por alguna que hay enfocada en Kotlin y mucho más modernas.

Pero bueno, si algún día me pongo en serio con el tema te avisaré.

Gracias, un saludo!
